### ISSUE TITLE
Directions to seed paper data appear outdated

### ISSUE THREAD

**Issue by thetechnocrat-dev** [ResearchHub/researchhub-backend#1569]
**Description**

The instructions mentioned in [Seed Paper Data ](https://github.com/ResearchHub/researchhub-backend/blob/master/README.md#seed-paper-data) appear outdated. The `pull_papers` and `pull_crossref_papers` do not seem to exist in the repo. 

**To Reproduce**
[Github search](https://github.com/search?q=repo%3AResearchHub%2Fresearchhub-backend+def+pull_papers&type=code) showing the `pull_papers` function is no longer found in the repo .

**Observed behavior**
I did try to use the `pull_new_openalex_works` task instead. I removed the `if not PRODUCTION` check. However, this returned a 403 when I tried running it locally. 

```
$ python ./manage.py shell_plus

In [1]: from paper.tasks import pull_new_openalex_works

In [2]: pull_new_openalex_works()
pulling new papers
/home/vscode/.local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1564: RuntimeWarning: DateTimeField PaperFetchLog.started_date received a naive datetime (2024-05-06 20:52:33.802372) while time zone support is active.
  warnings.warn(
/home/vscode/.local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1564: RuntimeWarning: DateTimeField PaperFetchLog.fetch_since_date received a naive datetime (2024-05-06 20:52:33.802372) while time zone support is active.
  warnings.warn(
Starting New OpenAlex pull: 1 None
403 Client Error: FORBIDDEN for url: https://api.openalex.org/works?filter=from_created_date%3A2024-05-06%2Ctype%3Aarticle&per-page=100&cursor=%2A&mailto=hello%40researchhub.com None Failed to pull new works from OpenAlex, retrying
Out[2]: False
```

The root reason I am asking about this is because I am getting an `negative index` 500 error when trying to run the frontend and backend together locally. I thought missing papers may be the cause. Below is the screenshot of the Django error when trying to hit the endpoint the frontend uses. 

<img width="1406" alt="Screenshot 2024-05-07 at 5 09 05 PM" src="https://github.com/ResearchHub/researchhub-backend/assets/9427089/06a9c9c5-7295-48f0-b8b5-d395d79c375c">

**Comment by gzurowski** [comment]
I have never used the process for seeding papers, and it's quite possible that the documentation is not accurate (or outdated). To bypass the negative index issue, please try manually uploading some papers as a workaround. You can do this through the web interface by selecting _+ New_, then _Upload Paper_, and either entering a paper URL or simply the DOI. After manually uploading  10+ papers, the problem should be resolved.

**Comment by yattias** [comment]
@thetechnocrat-dev we are working on a series of scripts to seed our database with OpenAlex data. 
Here is the issue to keep an eye on https://github.com/ResearchHub/researchhub-backend/issues/1575

**Comment by thetechnocrat-dev** [comment]
Thanks, I think that should work. Current hurdle is setting up a S3 bucket for my local instance to connect to. [LocalStack S3 ](https://docs.localstack.cloud/user-guide/aws/s3/) could be a nice onboard boost in the future. 



```
  File "/home/vscode/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 402, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: https://s3..amazonaws.com

HTTP POST /api/researchhubpost/? 500 [2.76, 127.0.0.1:46888]
```

**Comment by thetechnocrat-dev** [comment]
@yattias and @gzurowski I made a [draft PR](https://github.com/ResearchHub/researchhub-backend/pull/1593) to continue the conversation with what seems to be the actual root error of my local development. Please take a look when you get a chance.
