### ISSUE TITLE
Integrate with OpenZeppelin to speed up transaction settlement

### ISSUE THREAD

**Issue by yattias** [ResearchHub/researchhub-backend#1578]
Currently a background job that runs every five minutes is responsible for settlement. OpenZeppelin can speed things up and use a webhook

https://www.openzeppelin.com/

**Comment by koutst** [comment]
I tested OpenZeppelin in staging and it takes 5-15 minutes for the webhooks to come in. Our 5 minute polling almost always beats the webhooks. I don't think it's worth integrating.
