### ISSUE TITLE
Withdrawal complete notifications not being sent in production

### ISSUE THREAD

**Issue by koutst** [ResearchHub/researchhub-backend#1591]
**Description**
* Withdrawal completed notifications are not being sent in production.
* The testnet link is hardcoded in the code so even if a notification was sent it would be a link to the testnet.

**Staging notification**
<img width="439" alt="Screenshot 2024-05-10 at 11 07 24 AM" src="https://github.com/ResearchHub/researchhub-backend/assets/17444861/d1220548-73c6-4a70-8839-e7f3e25e65e9">

**Comment by yattias** [comment]
Moved to https://github.com/ResearchHub/issues/issues/24
